hard_tabs = true
use_field_init_shorthand = true
match_block_trailing_comma = true

condense_wildcard_suffixes = true
format_code_in_doc_comments = true
imports_granularity="Crate"
overflow_delimited_expr = true
reorder_impl_items = true
wrap_comments = true
